# Generated by Django 4.2.5 on 2023-09-18 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom')], max_length=2, verbose_name='country')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='followers count')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='following count')),
                ('playlist_count', models.PositiveBigIntegerField(default=0, verbose_name='playlist count')),
                ('is_premium', models.BooleanField(default=False, verbose_name='is premium')),
                ('premium_until', models.DateField(blank=True, verbose_name='premium until')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='FollowProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profiles.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
