# Generated by Django 4.2.5 on 2023-09-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
