# Generated by Django 4.2.5 on 2023-09-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
    ]
